name    := "orelang"
version := "1.0"
scalaVersion  := "2.12.0"
libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "1.0.4"
libraryDependencies += "org.scalaz" %% "scalaz-core" % "7.2.7"
